# Generated by Django 4.2.7 on 2025-12-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("sheng", "Sheng"),
                            ("swenglish", "Swenglish"),
                            ("english", "English"),
                        ],
                        default="swenglish",
                        max_length=20,
                    ),
                ),
                ("first_interaction", models.DateTimeField(auto_now_add=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                ("total_interactions", models.IntegerField(default=0)),
                ("telegram_username", models.CharField(blank=True, max_length=100)),
                ("whatsapp_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "unique_together": {("platform", "platform_user_id")},
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        max_length=20,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100)),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=100)),
                ("confidence", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["platform", "platform_user_id"],
                        name="bot_convers_platfor_20b32b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="bot_convers_timesta_0d0092_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
                        max_length=20,
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("telegram_message_id", models.CharField(blank=True, max_length=50)),
                ("whatsapp_message_id", models.CharField(blank=True, max_length=50)),
                ("mpesa_checkout_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="bot.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["platform", "customer"],
                        name="bot_appoint_platfor_4191cc_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="bot_appoint_schedul_284164_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bot_appoint_status_c61131_idx"
                    ),
                ],
            },
        ),
    ]
